sonata_form:
    form_type: standard

sonata_block:
    http_cache: false
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

services:
    admin.staff_user:
        class: App\Admin\PartAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Part, manager_type: orm, label: Parts }