sonata_form:
    form_type: standard

sonata_block:
    http_cache: false
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_admin:
    title: 'Sonata Admin'
    assets:
        extra_stylesheets:
            - app/css/admin.css
        extra_javascripts:
            - app/js/admin.js
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

services:
    admin.part:
        class: App\Admin\PartAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Part, manager_type: orm, label: Parts }
        calls:
            - [ setRouter, [ '@router' ] ]
            - [ setDataMapper, [ '@App\Form\DataMapper\PartDataMapper' ] ]

    admin.part_image:
        class: App\Admin\ImageAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\File\PartImage, manager_type: orm, label: Part Images }
        calls:
            - [ setFileSystemOperator, [ '@oneup_flysystem.default_filesystem_filesystem' ] ]
            - [ setTokenStorage, [ '@security.token_storage' ] ]