### get parts
GET https://ivan.alekseevich.popov.fvds.ru/api/parts

### get one part
GET https://ivan.alekseevich.popov.fvds.ru/api/parts/0186dbee-0f9a-7244-bec7-d5c0664615db

### get images of part
GET https://ivan.alekseevich.popov.fvds.ru/api/parts/0186dbee-0f9a-7244-bec7-d5c0664615db/images
